### ISSUE TITLE
codebase example

### ISSUE THREAD

**Issue by MMesch** [mast-group/naturalize#2]
Hi all,

Thank you for making this tool available! I have a simple question: The naturalize command line tools take a codebase as input. _How does such a codebase look like_? Is there an example somewhere?

This is everything that I found in the documentation:

> styleprofile accepts either a pre-trained language model or a codebase and trains a language model on that codebase. It then uses the trained language model for renaming. The type of identifiers for which suggestions will be made is controlled by the flags -m for method calls, -t for types and -v for variables.

**Comment by mallamanis** [comment]
I think that you're looking for this: https://github.com/mast-group/naturalize/blob/master/src/main/java/renaming/tools/FormattingReviewAssistant.java#L60
